name: Publish

on: workflow_dispatch

jobs:
  ci:
    name: Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: bazelbuild/setup-bazelisk@v1
    - name: Mount bazel cache
      uses: actions/cache@v2
      with:
        path: "~/.cache/bazel"
        key: bazel
   
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build, Test and Publish
      env:
        REGISTRY: docker.io
        PROJECT_ID: mobichord
      run: |
        set -ex
        bazel build --curses=no //package_manager:dpkg_parser.par
        bazel build --curses=no //java:java17_root_debian11
        bazel build --curses=no //java:java17_nonroot_debian11
        bazel test --curses=no --test_output=errors //java:java17_root_debian11_test
        bazel test --curses=no --test_output=errors //java:java17_nonroot_debian11_test
        bazel run //java:publish